version: '3.8'

services:
    postgres:
        image: postgres:17
        container_name: influencers_db
        restart: unless-stopped
        environment:
          POSTGRES_DB: influencers_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - "55432:5432"
        volumes:
          - postgres_data:/var/lib/postgresql/data
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -U postgres -d influencers_db"]
          interval: 10s
          timeout: 5s
          retries: 5
          start_period: 5s
    app:
      build: .
      ports:
        - "4040:4040"
      # context: .
      # dockerfile: Dockerfile
      environment:
        - PORT=4040
        - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/influencers_db
      depends_on:
        postgres:
          condition: service_healthy
 
volumes:
  postgres_data: